
-- Create Users Table to manage roles and departments
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  image TEXT,
  role TEXT DEFAULT 'user', -- 'admin' or 'user'
  department TEXT           -- e.g., 'BPH', 'Syiar', 'Kaderisasi', 'Media', 'Danus'
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Everyone can read users (for displaying authors, etc. - restrict if needed)
CREATE POLICY "Public users are viewable by everyone" 
ON public.users FOR SELECT 
USING (true);

-- 2. Only authenticated admins can insert/update/delete users
--    (We will use Service Role Key in Next.js API routes to bypass RLS for admin actions)
--    (For client-side safety, we can restrict this further, but Service Role is key here)

-- Initial Admin User (Optional - Change email to your admin email)
-- INSERT INTO public.users (email, name, role, department)
-- VALUES ('your.email@mail.ugm.ac.id', 'Super Admin', 'admin', 'BPH');
