
-- Create Posts Table
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL, -- URL friendly title
  excerpt TEXT,              -- Short description for cards
  content TEXT,              -- Full blog content (Rich Text / Markdown)
  category TEXT NOT NULL,
  author TEXT,
  image_url TEXT,            -- URL to cover image
  is_published BOOLEAN DEFAULT FALSE
);

-- Row Level Security (RLS) Policies
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view published posts
CREATE POLICY "Public posts are viewable by everyone" 
ON public.posts FOR SELECT 
USING (is_published = true);

-- Policy: Authenticated users can insert/update/delete posts (Assuming only admins login)
-- Ideally, checking email domain or role is better, but login is already restricted to @mail.ugm.ac.id
CREATE POLICY "authenticated users can modify posts" 
ON public.posts FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Dummy Data for Initial Population
INSERT INTO public.posts (title, slug, excerpt, content, category, author, image_url, is_published)
VALUES
(
  'Urgensi Menuntut Ilmu Bagi Mahasiswa Vokasi', 
  'urgensi-menuntut-ilmu-vokasi',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod.', 
  'Full content regarding urgency of knowledge...', 
  'Dakwah', 
  'Admin JAVA', 
  'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop',
  true
),
(
  'Refleksi Akhir Tahun: Apa yang Sudah Kita Berikan?', 
  'refleksi-akhir-tahun',
  'Refleksi diri sebagai mahasiswa di penghujung tahun.', 
  'Full reflection content here...', 
  'Internal', 
  'Admin JAVA', 
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2070&auto=format&fit=crop',
  true
),
(
  'Tips Manajemen Waktu Kuliah dan Organisasi', 
  'tips-manajemen-waktu',
  'Cara membagi waktu agar kuliah lancar dan organisasi jalan terus.', 
  'Full tips content here...', 
  'Vokasi', 
  'Admin JAVA', 
  'https://images.unsplash.com/photo-1513258496099-48168024aec0?q=80&w=2070&auto=format&fit=crop',
  true
);
